name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:

      - name: Set Artifact Name
        run: |
         
          echo $(Get-Date -Format dd.MM.yy) | Set-Variable DATE_N
          echo $DATE_N
          Set-Item -Path Env:ARTFC_NAME -Value "$DATE_N + "-Ext4Fsd""
          echo "filename: $Env:ARTFC_NAME"        
          
      - name: Show Variables
        run: 'dir Env:'
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
         name: ${{ env.FILE_NAME }}
         path: | 
            ${{ env.FILE_PATH1 }}
            ${{ env.FILE_PATH }}
            ${{ env.GITHUB_WORKSPACE }}
            
            
             
