name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DIR1: '*\Release\x64\Ext4Fsd\'
  DIR2: '*\Release\x64\Ext2Srv.exe'
  DIR3: '*\Release\x64\Ext2Mgr.exe'
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Ext4Fsd.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  
permissions:
  contents: read
  
jobs:
 build:  
  runs-on: windows-2019   

  steps:
  - uses: actions/checkout@v3

  - name: Chocolatey Install WinSDK
    uses: crazy-max/ghaction-chocolatey@v3.0.0
    with:
        args: install windows-sdk-10-version-2004-all --verbose --accept-license --confirm
    
  - name: Chocolatey Install WinWDK
    uses: crazy-max/ghaction-chocolatey@v3.0.0
    with:
          args: install windowsdriverkit10 --verbose --accept-license --confirm    
          
  - name: Add MSBuild to PATH
    uses: microsoft/setup-msbuild@v1.0.2

  - name: Restore NuGet packages
    working-directory: ${{env.GITHUB_WORKSPACE}}
    run: nuget restore ${{env.SOLUTION_FILE_PATH}}

  - name: Build
    working-directory: ${{env.GITHUB_WORKSPACE}}
    run: |
      msbuild  /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} /t:Build ${{env.SOLUTION_FILE_PATH}} 
    
      
  - name: SetArtifactName 
    id: SID1
    run: |
        set DATE_NOW -Value $(Get-Date -Format dd.MM.yy)
        echo $DATE_NOW
        set FILE_NAME -Value $($DATE_NoW + "-Ext4Fsd")
        echo "filename: $FILE_NAME"
        echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          
  - name: show ENV
    run: 'dir env:'

  - name: setPathforUpload
    id: SID2
    env: 
        PATH_1: ${{env.DIR1}}
        PATH_2: ${{env.DIR2}}
        PATH_3: ${{env.DIR3}}
    shell: pwsh  
    run: |
        echo $env:PATH_1
        echo $env:PATH_2
        echo $env:PATH_3         

  - name: ShowVariables
    id: SID3
    env: 
     working-directory: ${{env.GITHUB_WORKSPACE}}
     run: |
         echo $env:PATH_1
         echo $env:PATH_2
         echo $env:PATH_3
         echo $env:DIR1
         echo $env:DIR2 
         echo $env:DIR3         
  
  - uses: actions/upload-artifact@v3
    with:
      path: |
         D:\a\Ext4Fsd\Ext4Fsd\*\Release\x64\Ext4Fsd\
         D:\a\Ext4Fsd\Ext4Fsd\*\Release\x64\Ext2Srv.exe
         D:\a\Ext4Fsd\Ext4Fsd\*\Release\x64\Ext2Mgr.exe
