name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  
permissions:
  contents: read
  
jobs:
 build:  
     
   name: build_source
   runs-on: windows-2019 
   
   env:

      REPO_PATH: $GITHUB_WORKSPACE
      RELEASE_NAME: $ARTF_NAME
       
   steps:
   
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: SetArtifactName 
      id: set_file_name
      run: |
          echo $(Get-Date -Format dd.MM.yy) | Set-Variable DATE_NOW
          echo $DATE_NOW
          Set-Variable -Name FILE_NAME -Value ($DATE_NoW + "-Ext4Fsd")
          echo "filename: $FILE_NAME"
          echo "ARTF_NAME=$env:FILE_NAME" >> "$GITHUB_ENV"
          
    - name: show ENV
      run: 'dir env:'

    - name: setPathforUpload
      id: set_pathes
      shell: cmd pwsh {0}
      run: |         
    
         echo $env:GITHUB_WORKSPACE
         echo "REPO_PATH: ${{env.REPO_PATH}}"
         $env:DIR1="*\Release\x64\Ext4Fsd"
         $env:DIR2="*\Release\x64\Ext2Srv.exe" 
         $env:DIR3="*\Release\x64\Ext2Mgr.exe"
         echo "PATH_1=$env:DIR1" >> "$GITHUb_ENV"
         echo "PATH_2=$env:DIR2" >> "$GITHUB_ENV"
         echo "PATH_3=$env:DIR3" >> "$GITHUB_ENV"
         

    - name: ShowVariables
      run: |
         echo $env:PATH_1
         echo $env:PATH_2
         echo $env:PATH_3
         echo $PATH_1
         echo $PATH_2
         echo $PATH_3
         
        
    - name: Upload Artifact
      env:
       MY_PATH66: ${{ steps.step_one.env.MY_PATH6 }}
      uses: actions/upload-artifact@v3
      with:
          name: ${{env.FILE_NAME}}
          path: |
            ${{env.PATH_1}}
            ${{env.PATH_2}}      
            ${{env.PATH_3}}
            
