name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  FILE_NAME: "Arti"
  MY_PATH: "/sss/bbb"

permissions:
  contents: read
  

jobs:
  build:
   runs-on: windows-2019
   
   steps:    
  
    - name: SetArtifactName
      env:
        MY_PATH2: "/ggsd"
      run: |         
          echo $(Get-Date -Format dd.MM.yy) | Set-Variable DATE_NOW
          echo $DATE_NOW
          Set-Variable -Name ARTFC_NAME -Value ($DATE_NoW + "-Ext4Fsd")
          echo "filename: $ARTFC_NAME"
          echo "MY_PATH22: $env:MY_PATH2"          
          echo "MY_PATH22: ${{env.MY_PATH2}}"
          echo "filename3: ${{env.FILE_NAME}}"
          Set-Variable -Name env.MY_PATH2 -Value ("/fsssg")
          $env.MY_PATH2="/kkkkkk"
          $MY_PATH2="/aaaaa"
          ${env:MY_PATH2}="/fsssjkgjg"
          echo "_MY_PATH2: $MY_PATH2"
          echo "_env:MY_PATH2: ${env:MY_PATH2}"
          echo "_env.PATH2: ${{env.MY_PATH2}}"
          
    - name: Show Variables
      run: 'dir Env:'
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: ${{env.FILE_NAME}}
          path: |
            ${{env.MY_PATH}}
            ${{env.MY_PATH2}}             
