name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


  
permissions:
  contents: read
  
jobs:
 build:  
     
  runs-on: windows-2019   
       
  
  env:
  
    DIR1: '*\Release\x64\Ext4Fsd\'
    DIR2: '*\Release\x64\Ext2Srv.exe'
    DIR3: '*\Release\x64\Ext2Mgr.exe'

  steps:
   
  - name: Checkout
    uses: actions/checkout@v3
      
  - name: SetArtifactName 
    id: ID1
    run: |
          set DATE_NOW -Value $(Get-Date -Format dd.MM.yy)
          echo $DATE_NOW
          set FILE_NAME -Value $($DATE_NoW + "-Ext4Fsd")
          echo "filename: $FILE_NAME"
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          
  - name: show ENV
    run: 'dir env:'

  - name: setPathforUpload
    ID: ID2
    env: 
        PATH_1: ${{env.DIR_1}}
        PATH_2: ${{env.DIR_2}}
        PATH_3: ${{env.DIR_3}}
          
    shell: cmd pwsh {0}
    run: |
          echo $env:PATH_1
          echo $env:PATH_2
          echo $env:PATH_3

          echo "filename: $env:FILE_NAME"
         

  - name: ShowVariables
    run: ID3
    env: 
     working-directory: ${{env.GITHUB_WORKSPACE}}
     
         echo $env:PATH_1
         echo $env:PATH_2
         echo $env:PATH_3
         echo $env:DIR1
         echo $env:DIR2 
         echo $env:DIR3
         
        
  - name: Upload Artifact
    ID: ID3
     with:
      ARTF_NAME: ${{steps.ID1.outputs.file_name}}
    uses: actions/upload-artifact@v3
        name: $ARTF_NAME
        path: |
            ${{env.PATH_1}}
            ${{env.PATH_2}}      
            ${{env.PATH_3}}
            
