name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:

 REPO_PATH: ${env:GITHUB_WORKSPACE}
 OUT_PATH_1: ${{ steps.setPathforUpload.outputs.PATH_1 }}
 OUT_PATH_2: ${{ steps.setPathforUpload.outputs.PATH_2 }}
 OUT_PATH_3: ${{ steps.setPathforUpload.outputs.PATH_3 }}
 RELEASE_NAME: ${{ steps.set_file_name.outputs.ARTF_NAME }}
  
permissions:
  contents: read
  
jobs:
 build:  
     
   name: build_source
   runs-on: windows-2019     
      
   steps:
   
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: SetArtifactName 
      id: set_file_name
      run: |
          echo $(Get-Date -Format dd.MM.yy) | Set-Variable DATE_NOW
          echo $DATE_NOW
          Set-Variable -Name FILE_NAME -Value ($DATE_NoW + "-Ext4Fsd")
          echo "filename: $FILE_NAME"
          echo "ARTF_NAME=$FILE_NAME" >> $GITHUB_OUTPUT
          
    - name: show ENV
      run: 'dir env:'

    - name: setPathforUpload
      id: set_pathes
      run: |
         echo ("REPO_PATH: ${{env.REPO_PATH}}")
         echo "PATH_1=$($env:REPO_PATH+"*\Release\x64\Ext4Fsd\")" >> $GITHUB_OUTPUT
         echo "PATH_2=$($env:REPO_PATH+"*\Release\x64\Ext2Srv.exe")" >> $GITHUB_OUTPUT
         echo "PATH_3=$($env:REPO_PATH+"*\Release\x64\Ext2Mgr.exe")" >> $GITHUB_OUTPUT
         

    - name: ShowVariables
      run: |
         echo ${{env.OUT_PATH_1}}
         echo ${{env.OUT_PATH_2}}
         echo ${{env.OUT_PATH_3}}
         
        
    - name: Upload Artifact
      env:
       MY_PATH66: ${{ steps.step_one.env.MY_PATH6 }}
      uses: actions/upload-artifact@v3
      with:
          name: ${{env.FILE_NAME}}
          path: |
            ${{env.OUT_PATH_1}}
            ${{env.OUT_PATH_2}}      
            ${{env.OUT_PATH_3}}
            
