name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Ext4Fsd.sln

  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x64
  
permissions:
  contents: read
  
jobs:
 build:  
     
  runs-on: windows-2019   
        
  env:
  
    DIR1: '*\Release\x64\Ext4Fsd\'
    DIR2: '*\Release\x64\Ext2Srv.exe'
    DIR3: '*\Release\x64\Ext2Mgr.exe'

  steps:
   
  - name: Checkout
    uses: actions/checkout@v3
      
  - name: SetArtifactName 
    id: SID1
    run: |
        set DATE_NOW -Value $(Get-Date -Format dd.MM.yy)
        echo $DATE_NOW
        set FILE_NAME -Value $($DATE_NoW + "-Ext4Fsd")
        echo "filename: $FILE_NAME"
        echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          
  - name: show ENV
    run: 'dir env:'

  - name: setPathforUpload
    id: SID2
    env: 
        PATH_1: ${{env.DIR1}}
        PATH_2: ${{env.DIR2}}
        PATH_3: ${{env.DIR3}}
    shell: pwsh  
    run: |
        echo $env:PATH_1
        echo $env:PATH_2
        echo $env:PATH_3         

  - name: ShowVariables
    id: SID3
    env: 
     working-directory: ${{env.GITHUB_WORKSPACE}}
     run: |
         echo $env:PATH_1
         echo $env:PATH_2
         echo $env:PATH_3
         echo $env:DIR1
         echo $env:DIR2 
         echo $env:DIR3         
        
  - uses: actions/upload-artifact@v3
    env:
      ARTIF_NAMER: ${{ steps.SID1.outputs.file_name }}
    with:
      name: $ARTIF_NAME
      path: |
          ${{env.PATH_1}}
          ${{env.PATH_2}}      
          ${{env.PATH_3}}            
