name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:

  FILE_PATH1: $GITHUB_WORKSPACE
 
  FILE_NAME1: $ARTFC_NAME

  FILE_PATH: $GITHUB_WORKSPACE
  
  FILE_NAME: $ARTFC_NAME


 

permissions:
  contents: write
  actions: write

  

jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Artifact Name
      run: |
          echo $(Get-Date -Format dd.MM.yy) | set DATE_NOW;
          Set-Item -Path Env:ARTFC_NAME -Value $($DATE_NOW + "-Ext4Fsd");
          echo "filename: $Env:ARTFC_NAME";
          echo "work dir: $Env:GITHUB_WORKSPACE"
          echo "FILE_PATH1=$Env:GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "FILE_NAME1=$Env:ARTFC_NAME" >> $GITHUB_ENV
          echo "FILE_PATH: ${{ env.FILE_PATH1 }}"
          echo "FILE_NAME: ${{ env.FILE_NAME1 }}"
          Set-Item -Path Env:FILE_PATH -Value $Env:GITHUB_WORKSPACE
          Set-Item -Path Env:FILE_NAME -Value $Env:ARTFC_NAME
          echo "FILE_PATH2: $Env:FILE_PATH"
          echo "FILE_NAME2: $Env:FILE_NAME"

    - name: Show Variables
      run: 'dir Env:'
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{env.FILE_NAME1}}
        path: | 
            ${{ env.FILE_PATH1 }}
            ${Env:FILE_PATH}
            ${{ env.GITHUB_WORKSPACE }}
            ${Env:GITHUB_WORKSPACE}
            
             
