name: Testing

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  FILE_NAME: "Arti"
  MY_PATH: "/sss/bbb"
  

permissions:
  contents: read
  

jobs:
 build:
   env:
     MY_PATH2: "/ggsd"
     
   name: building
   runs-on: windows-2019
   steps:
    - name: SetArtifactName   
      run: |
          echo $(Get-Date -Format dd.MM.yy) | Set-Variable DATE_NOW
          echo $DATE_NOW
          Set-Variable -Name ARTFC_NAME -Value ($DATE_NoW + "-Ext4Fsd")
          echo "filename: $ARTFC_NAME"
          echo "_env:MY_PATH2: ${env:MY_PATH2}"
          echo "_env.PATH2: ${{env.MY_PATH2}}"
          echo "filename3: ${{env.FILE_NAME}}"
          
          echo "_env:MY_PATH2: ${env:MY_PATH2}"
          echo "_env.PATH2: ${{env.MY_PATH2}}"     
    - name: Show Variables
      run: 'dir Env:'

    - name: set Variables
      id: step_one
      run: |
          echo "MY_PATH3=hdhfhdh" >> "$GITHUB_OUTPUT"
      
    - name: Upload Artifact
      env:
       MY_PATH3: ${{ steps.step_one.outputs.MY_PATH3 }}
      uses: actions/upload-artifact@v3
      with:
          name: ${{env.FILE_NAME}}
          path: |
            ${{env.MY_PATH}}
            ${{env.MY_PATH2}}      
            $MY_PATH3
            
