name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
 

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
 

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set Artifact Name
      run: |
          echo $(Get-Date -Format dd.MM.yy) | set DATE_NOW;
          $ARTFC_NAME = $DATE_NOW + "-Ext4Fsd";
          echo $ARTFC_NAME;

    - name: Show Variables
      run: 'dir Env:'
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTFC_NAME }}
        path: | 
            ${{env.GITHUB_WORKSPACE}}\Setup\
             
