name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

 

permissions:
  contents: read


jobs:
  build:
    runs-on: windows-2019

    steps:
  

    - name: Set Artifact Name
      run: |
          echo $(Get-Date -Format dd.MM.yy) | set -Name $DATE_NOW;
          Set-Item -Path Env:ARTFC_NAME -Value "$DATE_NOW + "-Ext4Fsd"";
          echo "filename: $Env:ARTFC_NAME";
          echo "work dir: $Env:GITHUB_WORKSPACE";
          echo "filename: ${{env.ARTFC_NAME}};
          echo "work dir: ${{env.GITHUB_WORKSPACE}}";
          
          echo "FILE_PATH1=${{env.GITHUB_WORKSPACE}}" >> $GITHUB_ENV
          echo "FILE_NAME1=${{env.ARTFC_NAME}}" >> $GITHUB_ENV
          echo "FILE_PATH1: ${{env.FILE_PATH1}}"
          echo "FILE_NAME1: ${{env.FILE_NAME1}}"
          Set-Item -Path Env:FILE_PATH -Value $Env:GITHUB_WORKSPACE;
          Set-Item -Path Env:FILE_NAME -Value $Env:ARTFC_NAME;
          echo ""FILE_PATH:" + $Env:FILE_PATH";
          echo ""FILE_NAME:" + $Env:FILE_NAME";

    - name: Show Variables
      run: 'dir Env:'
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FILE_NAME }}
        path: | 
            ${{ env.FILE_PATH1 }}
            ${{ env.FILE_PATH }}
            ${{ env.GITHUB_WORKSPACE }}
            
            
             
