# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: Ext4Fsd.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x86

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Chocolatey Install WinSDK
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
          args: install windows-sdk-10-version-2004-all --verbose --accept-license --confirm
    
    - name: Chocolatey Install WinWDK
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
          args: install windowsdriverkit10 --verbose --accept-license --confirm    
          
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Show Variables
      run: 'dir Env:'

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild  /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} /t:Build ${{env.SOLUTION_FILE_PATH}}
